name: Process Results
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
    branches: [main]

jobs:
  process:
    name: process-results
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '8'
          architecture: x64

      - name: Generate report
        run: ./scripts/run-gatling-report.sh

      - name: Generate web page
        run: python ./scripts/generate-index.py
      
      - name: Commit report
        run: ./scripts/commit-report.sh

      - name: Analyze diff reports
        env:
          GOOGLE_CHAT_WEBHOOK: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        run: ./scripts/check-diff-reports.sh
